#!/usr/bin/env bun
/**
 * gen-core-types.ts — 빌드 전 실행. @clip/core 소스를 읽어
 * apps/clip/src/core-type-bundle.generated.ts 를 생성한다.
 *
 * 생성된 파일은 bun build --compile 시 바이너리에 포함되어,
 * clip ext scaffold / clip ext types 명령이 IDE 타입 파일을 배포할 때 사용한다.
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..");
const CORE_DIR = join(ROOT, "packages/core");
const OUT = join(ROOT, "apps/clip/src/core-type-bundle.generated.ts");

const FILES: Array<{ path: string; src: string }> = [
  { path: "package.json",                   src: "package.json" },
  { path: "src/index.ts",                   src: "src/index.ts" },
  { path: "src/extension.ts",               src: "src/extension.ts" },
  { path: "src/config.ts",                  src: "src/config.ts" },
  { path: "src/dispatch.ts",                src: "src/dispatch.ts" },
  { path: "src/acl.ts",                     src: "src/acl.ts" },
  { path: "src/alias.ts",                   src: "src/alias.ts" },
  { path: "src/output-registry.ts",         src: "src/output-registry.ts" },
  { path: "src/utils/errors.ts",            src: "src/utils/errors.ts" },
  { path: "src/utils/env-sub.ts",           src: "src/utils/env-sub.ts" },
  { path: "src/utils/output.ts",            src: "src/utils/output.ts" },
  { path: "src/utils/target-schema.ts",     src: "src/utils/target-schema.ts" },
  { path: "src/utils/tool-args.ts",         src: "src/utils/tool-args.ts" },
];

const entries = FILES.map(({ path, src }) => {
  const content = readFileSync(join(CORE_DIR, src), "utf8");
  return `  { path: ${JSON.stringify(path)}, content: ${JSON.stringify(content)} }`;
}).join(",\n");

const output = `// generated by scripts/gen-core-types.ts — do not edit manually
export type CoreTypeFile = { path: string; content: string };

export function getCoreTypeFiles(): CoreTypeFile[] {
  return [
${entries}
  ];
}
`;

writeFileSync(OUT, output, "utf8");
console.log(`[gen-core-types] → ${OUT.replace(ROOT + "/", "")}`);
